spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:salon_belleza;DB_CLOSE_DELAY=-1
    username: admin
    password: 1234
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: America/Bogota

server:
  address:  192.168.128.8
  port: 8080

logging:
  level:
    com.salon.belleza: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
