spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/salon_belleza
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Bogota

server:
  port: 8080

logging:
  level:
    com.salon.belleza: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE