-- ============================================================
-- SALON DE BELLEZA "SHALOM SOLO CEJAS"
-- Schema completo para Supabase (PostgreSQL)
--
-- ORDEN DE EJECUCIÓN:
-- 1. Ejecutar TODO este script en el SQL Editor de Supabase
-- 2. En Supabase Dashboard > Database > Replication, habilitar
--    Realtime para la tabla "servicios_realizados"
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- TABLAS
-- ────────────────────────────────────────────────────────────

-- Sedes (locaciones físicas del salón)
CREATE TABLE IF NOT EXISTS sedes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(100)  NOT NULL,
    direccion  VARCHAR(255)  NOT NULL,
    activa     BOOLEAN       NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Perfiles de usuario (extiende auth.users de Supabase)
CREATE TABLE IF NOT EXISTS perfiles (
    id                UUID         PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre            VARCHAR(150) NOT NULL,
    username          VARCHAR(50)  NOT NULL UNIQUE,
    rol               VARCHAR(20)  NOT NULL DEFAULT 'TRABAJADORA'
                                   CHECK (rol IN ('ADMIN', 'TRABAJADORA')),
    sede_principal_id BIGINT       NOT NULL REFERENCES sedes(id),
    activo            BOOLEAN      NOT NULL DEFAULT true,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Catálogo de servicios ofrecidos
CREATE TABLE IF NOT EXISTS catalogo_servicios (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(100)   NOT NULL,
    precio               NUMERIC(12, 2) NOT NULL CHECK (precio > 0),
    porcentaje_comision  NUMERIC(5, 2)  NOT NULL DEFAULT 50.00
                                        CHECK (porcentaje_comision >= 0 AND porcentaje_comision <= 100),
    activo               BOOLEAN        NOT NULL DEFAULT true,
    created_at           TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- Jornadas de trabajo (turnos)
CREATE TABLE IF NOT EXISTS jornadas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      UUID         NOT NULL REFERENCES perfiles(id),
    sede_id         BIGINT       NOT NULL REFERENCES sedes(id),
    fecha_apertura  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_cierre    TIMESTAMPTZ,
    estado          VARCHAR(10)  NOT NULL DEFAULT 'ABIERTA'
                                 CHECK (estado IN ('ABIERTA', 'CERRADA')),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- RESTRICCIÓN CRÍTICA: solo UNA jornada ABIERTA por usuario
CREATE UNIQUE INDEX IF NOT EXISTS uk_jornada_usuario_abierta
    ON jornadas (usuario_id)
    WHERE estado = 'ABIERTA';

CREATE INDEX IF NOT EXISTS idx_jornada_sede_fecha
    ON jornadas (sede_id, fecha_apertura);

-- Servicios realizados (registros de venta)
CREATE TABLE IF NOT EXISTS servicios_realizados (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jornada_id                    BIGINT         NOT NULL REFERENCES jornadas(id),
    servicio_id                   BIGINT         NOT NULL REFERENCES catalogo_servicios(id),
    cantidad                      INTEGER        NOT NULL CHECK (cantidad >= 1),
    -- Campos financieros (calculados por TRIGGER, inmutables)
    precio_unitario               NUMERIC(12, 2) NOT NULL,
    porcentaje_comision_aplicado  NUMERIC(5, 2)  NOT NULL,
    total_cobrado                 NUMERIC(12, 2) NOT NULL,
    comision_empleada             NUMERIC(12, 2) NOT NULL,
    total_caja_salon              NUMERIC(12, 2) NOT NULL,
    fecha_registro                TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sr_jornada ON servicios_realizados (jornada_id);
CREATE INDEX IF NOT EXISTS idx_sr_fecha   ON servicios_realizados (fecha_registro);


-- ────────────────────────────────────────────────────────────
-- TRIGGER: Cálculo seguro de valores financieros
-- Se ejecuta ANTES de insertar en servicios_realizados.
-- El frontend envía valores dummy (0); el trigger los reemplaza
-- con los valores reales del catálogo en ese instante.
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION calcular_financieros_servicio()
RETURNS TRIGGER AS $$
DECLARE
    v_precio   NUMERIC(12, 2);
    v_comision NUMERIC(5, 2);
BEGIN
    -- Obtener precio y comisión vigentes del catálogo
    SELECT precio, porcentaje_comision
    INTO v_precio, v_comision
    FROM catalogo_servicios
    WHERE id = NEW.servicio_id AND activo = true;

    IF v_precio IS NULL THEN
        RAISE EXCEPTION 'Servicio con id=% no encontrado o está inactivo.', NEW.servicio_id;
    END IF;

    -- Calcular y congelar valores financieros
    NEW.precio_unitario              := v_precio;
    NEW.porcentaje_comision_aplicado := v_comision;
    NEW.total_cobrado                := v_precio * NEW.cantidad;
    NEW.comision_empleada            := ROUND(NEW.total_cobrado * v_comision / 100, 2);
    NEW.total_caja_salon             := NEW.total_cobrado - NEW.comision_empleada;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER trg_calcular_financieros
    BEFORE INSERT ON servicios_realizados
    FOR EACH ROW
    EXECUTE FUNCTION calcular_financieros_servicio();


-- ────────────────────────────────────────────────────────────
-- FUNCIÓN: Resumen de caja por sede (solo admin)
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION resumen_caja_sede_hoy(p_sede_id BIGINT)
RETURNS TABLE (
    sede_nombre          VARCHAR,
    trabajadoras_activas BIGINT,
    total_producido      NUMERIC,
    total_comisiones     NUMERIC,
    total_caja_salon     NUMERIC
) AS $$
BEGIN
    -- Solo administradores
    IF NOT EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol = 'ADMIN') THEN
        RAISE EXCEPTION 'Solo administradores pueden consultar la caja.';
    END IF;

    RETURN QUERY
    SELECT
        s.nombre::VARCHAR                     AS sede_nombre,
        (
            SELECT COUNT(*)
            FROM jornadas j2
            WHERE j2.sede_id = p_sede_id
              AND j2.estado  = 'ABIERTA'
        )::BIGINT                             AS trabajadoras_activas,
        COALESCE(SUM(sr.total_cobrado), 0)    AS total_producido,
        COALESCE(SUM(sr.comision_empleada), 0) AS total_comisiones,
        COALESCE(SUM(sr.total_caja_salon), 0)  AS total_caja_salon
    FROM sedes s
    LEFT JOIN jornadas j
        ON j.sede_id = s.id
    LEFT JOIN servicios_realizados sr
        ON sr.jornada_id = j.id
       AND sr.fecha_registro::date = CURRENT_DATE
    WHERE s.id = p_sede_id
    GROUP BY s.nombre;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ────────────────────────────────────────────────────────────
-- FUNCIÓN: Resumen de la jornada activa del usuario actual
-- Usa auth.uid() internamente → no se puede espiar a otros.
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION mi_resumen_jornada()
RETURNS JSON AS $$
DECLARE
    v_user_id    UUID;
    v_jornada_id BIGINT;
    v_result     JSON;
BEGIN
    v_user_id := auth.uid();

    -- Buscar jornada abierta
    SELECT id INTO v_jornada_id
    FROM jornadas
    WHERE usuario_id = v_user_id AND estado = 'ABIERTA';

    IF v_jornada_id IS NULL THEN
        RETURN '{"servicios":[],"granTotalCobrado":0,"granTotalComision":0,"granTotalCajaSalon":0}'::json;
    END IF;

    SELECT json_build_object(
        'jornadaId', v_jornada_id,
        'servicios', COALESCE((
            SELECT json_agg(json_build_object(
                'servicioNombre', sub.nombre,
                'cantidadTotal',  sub.cnt,
                'totalCobrado',   sub.tc,
                'totalComision',  sub.ce,
                'totalCajaSalon', sub.tcs
            ))
            FROM (
                SELECT cs.nombre,
                       SUM(sr.cantidad)         AS cnt,
                       SUM(sr.total_cobrado)     AS tc,
                       SUM(sr.comision_empleada) AS ce,
                       SUM(sr.total_caja_salon)  AS tcs
                FROM servicios_realizados sr
                JOIN catalogo_servicios cs ON cs.id = sr.servicio_id
                WHERE sr.jornada_id = v_jornada_id
                GROUP BY cs.nombre
                ORDER BY cs.nombre
            ) sub
        ), '[]'::json),
        'granTotalCobrado',   COALESCE((SELECT SUM(total_cobrado)     FROM servicios_realizados WHERE jornada_id = v_jornada_id), 0),
        'granTotalComision',  COALESCE((SELECT SUM(comision_empleada) FROM servicios_realizados WHERE jornada_id = v_jornada_id), 0),
        'granTotalCajaSalon', COALESCE((SELECT SUM(total_caja_salon)  FROM servicios_realizados WHERE jornada_id = v_jornada_id), 0)
    ) INTO v_result;

    RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ────────────────────────────────────────────────────────────
-- TRIGGER: Crear perfil automáticamente al registrar usuario
-- Se dispara cuando Supabase Auth crea un user en auth.users.
-- Lee nombre, username, rol y sede desde raw_user_meta_data.
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO perfiles (id, nombre, username, rol, sede_principal_id)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data ->> 'nombre',            'Sin nombre'),
        COALESCE(NEW.raw_user_meta_data ->> 'username',          split_part(NEW.email, '@', 1)),
        COALESCE(NEW.raw_user_meta_data ->> 'rol',               'TRABAJADORA'),
        COALESCE((NEW.raw_user_meta_data ->> 'sede_principal_id')::bigint, 1)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Conectar trigger a auth.users
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION handle_new_user();


-- ────────────────────────────────────────────────────────────
-- FUNCIÓN AUXILIAR: ¿El usuario actual es admin?
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM perfiles
        WHERE id = auth.uid() AND rol = 'ADMIN'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;


-- ────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY (RLS)
-- ────────────────────────────────────────────────────────────

ALTER TABLE sedes                ENABLE ROW LEVEL SECURITY;
ALTER TABLE perfiles             ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalogo_servicios   ENABLE ROW LEVEL SECURITY;
ALTER TABLE jornadas             ENABLE ROW LEVEL SECURITY;
ALTER TABLE servicios_realizados ENABLE ROW LEVEL SECURITY;

-- ── SEDES ─────────────────────────────────────────────────
-- Todos pueden leer sedes activas; solo admin puede modificar
CREATE POLICY "sedes_lectura_todos"
    ON sedes FOR SELECT
    USING (true);

CREATE POLICY "sedes_admin_total"
    ON sedes FOR ALL
    USING (is_admin());

-- ── PERFILES ──────────────────────────────────────────────
-- Cada usuario ve su propio perfil; admin ve todos
CREATE POLICY "perfiles_lectura"
    ON perfiles FOR SELECT
    USING (id = auth.uid() OR is_admin());

CREATE POLICY "perfiles_update_propio"
    ON perfiles FOR UPDATE
    USING (id = auth.uid() OR is_admin());

-- ── CATÁLOGO ──────────────────────────────────────────────
-- Todos pueden leer; solo admin puede gestionar
CREATE POLICY "catalogo_lectura_todos"
    ON catalogo_servicios FOR SELECT
    USING (true);

CREATE POLICY "catalogo_admin_total"
    ON catalogo_servicios FOR ALL
    USING (is_admin());

-- ── JORNADAS ──────────────────────────────────────────────
-- Cada trabajadora ve sus propias jornadas; admin ve todas
CREATE POLICY "jornadas_lectura"
    ON jornadas FOR SELECT
    USING (usuario_id = auth.uid() OR is_admin());

-- Solo puede insertar jornadas propias
CREATE POLICY "jornadas_insertar_propia"
    ON jornadas FOR INSERT
    WITH CHECK (usuario_id = auth.uid());

-- Solo puede actualizar sus jornadas (o admin)
CREATE POLICY "jornadas_actualizar"
    ON jornadas FOR UPDATE
    USING (usuario_id = auth.uid() OR is_admin());

-- ── SERVICIOS REALIZADOS ──────────────────────────────────
-- Ver solo servicios de jornadas propias (o admin ve todo)
CREATE POLICY "sr_lectura"
    ON servicios_realizados FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM jornadas j
            WHERE j.id = jornada_id
              AND (j.usuario_id = auth.uid() OR is_admin())
        )
    );

-- Insertar solo en jornada propia y abierta
CREATE POLICY "sr_insertar_jornada_propia"
    ON servicios_realizados FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM jornadas j
            WHERE j.id = jornada_id
              AND j.usuario_id = auth.uid()
              AND j.estado = 'ABIERTA'
        )
    );


-- ────────────────────────────────────────────────────────────
-- SUPABASE REALTIME
-- Habilitar la publicación en tiempo real para las tablas clave
-- ────────────────────────────────────────────────────────────

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND tablename = 'servicios_realizados'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE servicios_realizados;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND tablename = 'jornadas'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE jornadas;
    END IF;
END $$;


-- ────────────────────────────────────────────────────────────
-- DATOS INICIALES (SEED)
-- ────────────────────────────────────────────────────────────

-- Sedes de ejemplo
INSERT INTO sedes (nombre, direccion, activa) VALUES
    ('Sede Centro',    'Calle 10 # 5-20, Centro',   true),
    ('Sede Norte',     'Av. 68 # 120-30, Usaquén',  true),
    ('Sede Occidente', 'Cra. 80 # 15-40, Fontibón', true)
ON CONFLICT DO NOTHING;

-- Catálogo de servicios
INSERT INTO catalogo_servicios (nombre, precio, porcentaje_comision, activo) VALUES
    ('Uñas Acrílicas',       85000.00, 50.00, true),
    ('Uñas en Gel',          70000.00, 50.00, true),
    ('Manicure',             25000.00, 50.00, true),
    ('Pedicure',             30000.00, 50.00, true),
    ('Cejas (Depilación)',   15000.00, 50.00, true),
    ('Cejas (Diseño)',       20000.00, 50.00, true),
    ('Depilación Facial',    20000.00, 50.00, true),
    ('Depilación Cuerpo',    40000.00, 50.00, true),
    ('Pestañas (Lifting)',   60000.00, 55.00, true),
    ('Pestañas (Extensión)', 90000.00, 55.00, true),
    ('Tinte de Cejas',       25000.00, 50.00, true)
ON CONFLICT DO NOTHING;


-- ────────────────────────────────────────────────────────────
-- USUARIOS DE PRUEBA
-- Credenciales:
--   admin         / admin123   → Rol ADMIN
--   maria.garcia  / 1234       → Rol TRABAJADORA (Sede Centro)
--   ana.martinez  / 1234       → Rol TRABAJADORA (Sede Norte)
--
-- El trigger on_auth_user_created crea el perfil automáticamente.
-- ────────────────────────────────────────────────────────────

-- Admin (admin / admin123)
DO $$
DECLARE v_uid UUID;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'admin@salon.app') THEN
        INSERT INTO auth.users (
            instance_id, id, aud, role, email,
            encrypted_password, email_confirmed_at,
            raw_user_meta_data, created_at, updated_at
        ) VALUES (
            '00000000-0000-0000-0000-000000000000',
            gen_random_uuid(), 'authenticated', 'authenticated',
            'admin@salon.app',
            crypt('admin123', gen_salt('bf')),
            now(),
            jsonb_build_object(
                'nombre', 'Administradora',
                'username', 'admin',
                'rol', 'ADMIN',
                'sede_principal_id', 1
            ),
            now(), now()
        ) RETURNING id INTO v_uid;

        INSERT INTO auth.identities (
            id, user_id, identity_data, provider, provider_id,
            created_at, updated_at, last_sign_in_at
        ) VALUES (
            gen_random_uuid(), v_uid,
            jsonb_build_object('sub', v_uid::text, 'email', 'admin@salon.app'),
            'email', v_uid::text,
            now(), now(), now()
        );
    END IF;
END $$;

-- Trabajadora 1 (maria.garcia / 1234)
DO $$
DECLARE v_uid UUID;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'maria.garcia@salon.app') THEN
        INSERT INTO auth.users (
            instance_id, id, aud, role, email,
            encrypted_password, email_confirmed_at,
            raw_user_meta_data, created_at, updated_at
        ) VALUES (
            '00000000-0000-0000-0000-000000000000',
            gen_random_uuid(), 'authenticated', 'authenticated',
            'maria.garcia@salon.app',
            crypt('1234', gen_salt('bf')),
            now(),
            jsonb_build_object(
                'nombre', 'María García',
                'username', 'maria.garcia',
                'rol', 'TRABAJADORA',
                'sede_principal_id', 1
            ),
            now(), now()
        ) RETURNING id INTO v_uid;

        INSERT INTO auth.identities (
            id, user_id, identity_data, provider, provider_id,
            created_at, updated_at, last_sign_in_at
        ) VALUES (
            gen_random_uuid(), v_uid,
            jsonb_build_object('sub', v_uid::text, 'email', 'maria.garcia@salon.app'),
            'email', v_uid::text,
            now(), now(), now()
        );
    END IF;
END $$;

-- Trabajadora 2 (ana.martinez / 1234)
DO $$
DECLARE v_uid UUID;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'ana.martinez@salon.app') THEN
        INSERT INTO auth.users (
            instance_id, id, aud, role, email,
            encrypted_password, email_confirmed_at,
            raw_user_meta_data, created_at, updated_at
        ) VALUES (
            '00000000-0000-0000-0000-000000000000',
            gen_random_uuid(), 'authenticated', 'authenticated',
            'ana.martinez@salon.app',
            crypt('1234', gen_salt('bf')),
            now(),
            jsonb_build_object(
                'nombre', 'Ana Martínez',
                'username', 'ana.martinez',
                'rol', 'TRABAJADORA',
                'sede_principal_id', 2
            ),
            now(), now()
        ) RETURNING id INTO v_uid;

        INSERT INTO auth.identities (
            id, user_id, identity_data, provider, provider_id,
            created_at, updated_at, last_sign_in_at
        ) VALUES (
            gen_random_uuid(), v_uid,
            jsonb_build_object('sub', v_uid::text, 'email', 'ana.martinez@salon.app'),
            'email', v_uid::text,
            now(), now(), now()
        );
    END IF;
END $$;


-- ════════════════════════════════════════════════════════════
-- ✅ LISTO. Schema, triggers, RLS, funciones y datos iniciales
--    han sido creados correctamente.
--
-- Usuarios de prueba:
--   admin         / admin123
--   maria.garcia  / 1234
--   ana.martinez  / 1234
-- ════════════════════════════════════════════════════════════
